# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

segment <- function(w_vector, c_vector, gap_size = 500L, thresh = 0.01) {
    .Call(`_numap_segment`, w_vector, c_vector, gap_size, thresh)
}

unique_M_one_seg <- function(a, wsize, seg_start) {
    .Call(`_numap_unique_M_one_seg`, a, wsize, seg_start)
}

unique_M_one_seg_long <- function(a, wsize, seg_start) {
    .Call(`_numap_unique_M_one_seg_long`, a, wsize, seg_start)
}

unique_M2 <- function(a, seg_start, seg_end, wsize = 120L) {
    .Call(`_numap_unique_M2`, a, seg_start, seg_end, wsize)
}

NCP_cal_poisson <- function(w_vector, c_vector, temp1, ite_num) {
    .Call(`_numap_NCP_cal_poisson`, w_vector, c_vector, temp1, ite_num)
}

NCP_cal_poisson_4 <- function(seq1, w_vector, c_vector, temp4, ite_num) {
    .Call(`_numap_NCP_cal_poisson_4`, seq1, w_vector, c_vector, temp4, ite_num)
}

train4 <- function(seq1, w_vector, c_vector, umap) {
    .Call(`_numap_train4`, seq1, w_vector, c_vector, umap)
}

train42 <- function(seq1, w_vector, c_vector, umap) {
    .Call(`_numap_train42`, seq1, w_vector, c_vector, umap)
}

linker_cal <- function(umap) {
    .Call(`_numap_linker_cal`, umap)
}

auto_corr <- function(rmap, max_lag) {
    .Call(`_numap_auto_corr`, rmap, max_lag)
}

occu_cal <- function(pos, score, weights, chrom_len) {
    .Call(`_numap_occu_cal`, pos, score, weights, chrom_len)
}

occu_cal_M_paired_center <- function(start, end, weights, score, chrom_len) {
    .Call(`_numap_occu_cal_M_paired_center`, start, end, weights, score, chrom_len)
}

occu_cal_M_paired_unif <- function(start, end, chrom_len) {
    .Call(`_numap_occu_cal_M_paired_unif`, start, end, chrom_len)
}

temp_update <- function(temp1, w_vector, c_vector) {
    .Call(`_numap_temp_update`, temp1, w_vector, c_vector)
}

occu_TSS_cal <- function(occu, pos, strand, region) {
    .Call(`_numap_occu_TSS_cal`, occu, pos, strand, region)
}

AATT_cal <- function(seq1, pos, region) {
    .Call(`_numap_AATT_cal`, seq1, pos, region)
}

